# Generated by Django 2.2.28 on 2024-04-09 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=60)),
                ('zuzendaria', models.CharField(max_length=60)),
                ('urtea', models.IntegerField()),
                ('generoa', models.CharField(max_length=2)),
                ('sinopsia', models.CharField(max_length=700)),
                ('bozkak', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bozkatzailea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gogoko_filmak', models.ManyToManyField(related_name='bozkatzaileak', to='app.Filma')),
            ],
        ),
    ]
